### ISSUE TITLE
Cositas

### ISSUE THREAD

**Issue by facuariasla** [juanmartin1601/juanmartin1601.github.io#1]
Hola juanma, muy piola te quedo me gusto como aplicaste grid a casi todo y te quedo bastante ordenado, por lo que veo la pagina no se rompe (como me paso a mi). Lo único como para corregirte algo seria el tamaño de algunas fuentes del nav en el header a un poco mas grandes quizás pero es mas subjetivo todo esto; o el box 2 (sobre mi) que sea un poco mas grande pero después todo joya te quedo muy bueno
Un saludo y suerte en el modulo 4**

**Comment by juanmartin1601** [comment]
Hola Facu muchas gracias por el feedback, tomo lo que me decís así lo mejoro para la prox, un abrazo y éxitos para vos también
